version: '3'

volumes:
  local_postgres_data: {}

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

