version: '3'

volumes:
  local_postgres_data: {}

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env.local
    ports:
      - 333:80
    depends_on:
      - db

  backend:
    build: .
    ports:
      - "8003:8003"
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload