"""change product

Revision ID: 43297bb9bdf8
Revises: 6ce8e8a39ccd
Create Date: 2024-06-07 19:15:36.445830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43297bb9bdf8'
down_revision = '6ce8e8a39ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
